<?php

use App\Domain\Businesses\Enums\BusinessMemberRole;

return [
    'invitation_expiry_days' => (int) env('REZERA_STAFF_INVITATION_EXPIRY_DAYS', 14),

    'suggested_job_titles' => [
        'Administrator',
        'Reception Staff',
        'Operator',
        'Floor Manager',
        'Host',
    ],

    'role_labels' => [
        BusinessMemberRole::Owner->value => 'Owner',
        BusinessMemberRole::Manager->value => 'Manager',
        BusinessMemberRole::Staff->value => 'Staff',
    ],

    'permissions' => [
        'view_management',
        'manage_business',
        'manage_working_hours',
        'view_members',
        'manage_members',
        'invite_staff',
        'add_manager',
        'manage_resources',
        'operate_bookings',
        'administer_bookings',
        'manage_reservation_settings',
        'manage_subscription',
        'manage_verification',
        'view_analytics',
        'manage_promo_codes',
        'manage_loyalty',
        'leave_business',
    ],

    'role_permissions' => [
        BusinessMemberRole::Owner->value => [
            'view_management' => true,
            'manage_business' => true,
            'manage_working_hours' => true,
            'view_members' => true,
            'manage_members' => true,
            'invite_staff' => true,
            'add_manager' => true,
            'manage_resources' => true,
            'operate_bookings' => true,
            'administer_bookings' => true,
            'manage_reservation_settings' => true,
            'manage_subscription' => true,
            'manage_verification' => true,
            'view_analytics' => true,
            'manage_promo_codes' => true,
            'manage_loyalty' => true,
            'leave_business' => false,
        ],
        BusinessMemberRole::Manager->value => [
            'view_management' => true,
            'manage_business' => true,
            'manage_working_hours' => true,
            'view_members' => true,
            'manage_members' => true,
            'invite_staff' => true,
            'add_manager' => false,
            'manage_resources' => true,
            'operate_bookings' => true,
            'administer_bookings' => true,
            'manage_reservation_settings' => true,
            'manage_subscription' => true,
            'manage_verification' => true,
            'view_analytics' => true,
            'manage_promo_codes' => true,
            'manage_loyalty' => true,
            'leave_business' => true,
        ],
        BusinessMemberRole::Staff->value => [
            'view_management' => true,
            'manage_business' => false,
            'manage_working_hours' => false,
            'view_members' => false,
            'manage_members' => false,
            'invite_staff' => false,
            'add_manager' => false,
            'manage_resources' => false,
            'operate_bookings' => true,
            'administer_bookings' => false,
            'manage_reservation_settings' => false,
            'manage_subscription' => false,
            'manage_verification' => false,
            'view_analytics' => false,
            'manage_promo_codes' => false,
            'manage_loyalty' => false,
            'leave_business' => true,
        ],
    ],
];
